document.addEventListener("DOMContentLoaded", () => {

    (() => {
    //If you want to add more images, add the link name and URL image URL in the array list below.
        const images_list = [
    {
        "url": "/imagenes/slide1.png",
        "alt": "",
        "name": "slide1.png",
        "link": ""
    },
    {
        "url": "/imagenes/slide2.png",
        "alt": "",
        "name": "slide2.png",
        "link": ""
    }
        ];
    
    // generated by https://www.html-code-generator.com/html/image-slideshow-generator
        let slider_id = document.querySelector("#carrouselImagenes");
    
        // append all images
        let dots_div = "";
        let images_div = "";
        for (let i = 0; i < images_list.length; i++) {
            // if no link without href="" tag
            let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
            images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
                            '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
                         '</a>';
        }
        slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
        let slide_index = 0;
    
        const images = slider_id.querySelectorAll(".hcg-slides");
        const prev_button = slider_id.querySelector("#hcg-slide-prev");
        const next_button = slider_id.querySelector("#hcg-slide-next");
    
        const showSlides = () => {
            if (slide_index > images.length-1) {
                slide_index = 0;
            }
            if (slide_index < 0) {
                slide_index = images.length-1;
            }
            for (let i = 0; i < images.length; i++) {
                images[i].style.display = "none";
                if (i == slide_index) {
                    images[i].style.display = "flex";
                }
            }
        }
    
        prev_button.addEventListener("click", event => {
            event.preventDefault();
            slide_index--;
            showSlides();
        }, false);
    
        next_button.addEventListener("click", event => {
            event.preventDefault();
            slide_index++;
            showSlides();
        }, false);
    
    })();
    

//Carousel Testimonios//
let index = 0;
const images = document.querySelectorAll('.carousel img');

setInterval(() => {
    index++;
    if (index > images.length - 1) {
    index = 0;
    }
    images.forEach(img => {
    img.classList.remove('active');
    });
    images[index].classList.add('active');
}, 10000);

//mensaje de consulta enviada
var contacto_form = document.getElementById("contacto-form");
var formulario_enviado = document.getElementById("formulario-enviado");
var formulario_no_enviado = document.getElementById("fomulario-no-enviado");

var contacto_input = document.getElementById("contacto-input");
var email_input = document.getElementById("email-input");

var enviar_consulta = document.getElementById("boton-enviar");

function mostrar_elemento(ocultar_actual, mostrar_siguiente) {
    ocultar_actual.style.display = "none";
    mostrar_siguiente.style.display = "flex";
}

enviar_consulta.addEventListener("click", function (e) {
    if (contacto_input.value && email_input.value) {
        mostrar_elemento(contacto_form, formulario_enviado)
        e.preventDefault();
    } else{
        formulario_no_enviado.style.display = "flex";
    }

})

// formulario cotizacion

var seg = document.getElementById("seg"); // boton siguiente
var prim = document.getElementById("prim"); // boton anterior

var secCotiz = document.getElementById("cotizacion"); // <seccion> cotizacion
var formsCotiz = secCotiz.querySelectorAll("#form");  // node list de todos los <divs> con id #form de la <seccion> cotizacion


seg.addEventListener("click", () => {  // cuando clikeo el boton siguiente
        
    var formActivo = secCotiz.querySelector(".visible");  // form que tenga clase "visible"
        
    var formSiguiente = secCotiz.querySelector(".visible + .invisible"); // el form que le sigue al que tiene clase visible

    
    if(formSiguiente === null){  // si llega al ultimo form del conjunto de secCotiz
        formSiguiente = formsCotiz.querySelector(".invisible:first-of-type"); // desactiva el primer form??
    }  // esto es para que vuelva a empezar (?)
    
        
     formActivo.classList.remove("visible");     // le saco la clase visible al primer form que es el que la tiene
     formActivo.classList.add("invisible");     // le doy clase invisible

     formSiguiente.classList.remove("invisible");  // al form siguiente le saco .invisible
     formSiguiente.classList.add("visible");        // y le doy .visible
        
});

// quiero iterar sobre la node list formsCotiz de elementos form
// una node list solo se puede iterar con el metodo .forEach
// entonces solo uso el valor de length de formsCotiz para tener el numero indice de cada elemento

prim.addEventListener("click", () => {

    for (var i = 0; i < formsCotiz.length; i ++){  
    // console.log(formsCotiz.item(i).classList);

    if (formsCotiz.item(i).classList.contains("visible") === true){
        break;
    }               // si el elemento en el indice tiene clase visible, salir del for
    }

    var posicionAnterior = i-1; // => la posicion del elemento desactivo anterior

    if(posicionAnterior === -1){
        posicionAnterior = formsCotiz.length-1; // => voy a la posicion del ultimo elemento
    }


    formsCotiz.item(i).classList.remove("visible");
    formsCotiz.item(i).classList.add("invisible");

    formsCotiz.item(posicionAnterior).classList.remove("invisible");
    formsCotiz.item(posicionAnterior).classList.add("visible");

});



}); // cierre del DOMcontentloaded


